-- Migration: align_prisma_managed_defaults
--
-- Purpose:
--   Remove database-level column defaults that conflict with Prisma
--   Client-managed values. These defaults were introduced on a fresh
--   database by migration 20260612000000_add_public_registration_approval,
--   but schema.prisma declares these columns as Client-managed, so the
--   database should carry NO default for them.
--
-- Rationale:
--   * MembershipPermission.id and RegistrationRequest.id use Prisma
--     @default(cuid()). cuid() is generated by Prisma Client, not by
--     PostgreSQL, so a database default of gen_random_uuid()::text is
--     incorrect and must be dropped.
--   * RegistrationRequest.updatedAt uses Prisma @updatedAt, which is
--     maintained by Prisma Client on every write. A database default of
--     CURRENT_TIMESTAMP is incorrect and must be dropped.
--   * The existing maos_db already has NO defaults on these three columns;
--     this migration only aligns fresh installations to match both
--     schema.prisma and the current database.
--
-- Safety:
--   * DROP DEFAULT is idempotent-safe: dropping a default that is already
--     absent is a no-op in PostgreSQL and does not error.
--   * No data is read, updated, inserted, or deleted.
--   * No column type, nullability, constraint, or index is changed.

-- 1. MembershipPermission.id — drop gen_random_uuid() default (Prisma cuid())
ALTER TABLE "MembershipPermission" ALTER COLUMN "id" DROP DEFAULT;

-- 2. RegistrationRequest.id — drop gen_random_uuid() default (Prisma cuid())
ALTER TABLE "RegistrationRequest" ALTER COLUMN "id" DROP DEFAULT;

-- 3. RegistrationRequest.updatedAt — drop CURRENT_TIMESTAMP default (Prisma @updatedAt)
ALTER TABLE "RegistrationRequest" ALTER COLUMN "updatedAt" DROP DEFAULT;
